FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache curl

# package.json과 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 나머지 소스 코드 복사 (볼륨 마운트로 오버라이드됨)
COPY . .

VOLUME ["/app"]
CMD ["npm", "run", "dev"]