global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 스프링부트 백엔드 메트릭 수집
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'example-backend-1:8080'
        - 'example-backend-2:8080'
    scrape_timeout: 5s

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
