name: Deploy frontend for production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, frontend, Production ]
    steps:
      - name: Deploy with docker-compose
        run: |
          cd /opt/docker/projects/example/frontend
          bash ./deploy.sh