name: Deploy for production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, backend, Production ]
    steps:
      - name: Deploy with docker-compose
        run: |
          cd /opt/docker/projects/pincoin/backend
          bash ./deploy.sh